### ISSUE TITLE
SM0805-Jumper

### ISSUE THREAD

**Issue by rusefillc** [rusefi/kicad6-libraries#13]
у нас в старой библиотеке есть https://github.com/rusefi/kicad-libraries/blob/master/SM0805-Jumper.mod

хочется положить в эту библиотеку его kicad6/7 версию

**Comment by rusefillc** [comment]
@Qwerty-OFF или у нас есть уже hellen-one-common:PAD-0805-PAD ? это какой файл где? в целом хочется создавать платы с зависимостью ТОЛЬКО на kicad6-libraries без других библиотек

**Comment by Qwerty-OFF** [comment]
Он в hellen-one лежит, там ещё сколько-то компонентов есть

**Comment by rusefillc** [comment]
@Qwerty-OFF можешь скопировать? потому что я не понимаю банально, какой файл. NET-JUMPER?

**Comment by Qwerty-OFF** [comment]
https://github.com/andreika-git/hellen-one/blob/master/kicad%2Fhellen-one-common.kicad_sym
И рядом папка footprints

**Comment by Qwerty-OFF** [comment]
Перенес из hellen-one
