### ISSUE TITLE
uaefi symbol: семь отверстий в висящий угол

### ISSUE THREAD

**Issue by rusefillc** [rusefi/kicad6-libraries#14]
у нас нижний-правый bluetooth угол в воздухе может повиснуть - давай просто продублируем на компоненте 1x5 USB и uart TX/RX пины, будет возможность какие-то их них паять для монтажа этого угла

![image](https://github.com/rusefi/kicad6-libraries/assets/48498823/371f161c-6cbb-4db7-80f8-cad2d9f753d9)

https://raw.githubusercontent.com/rusefi/uaefi/master/docs/uaefi-a-top.png

**Comment by Ringenium** [comment]
@rusefillc если дублировать контакты, то нужно туда 2.54 ставить, вот в эти зоны, как мне видится 
![image](https://github.com/rusefi/kicad6-libraries/assets/58686541/43e08364-9e95-4290-834c-d4dd6658cd5e)

**Comment by rusefillc** [comment]
@Ringenium мой аргумент - мой вариант проще. никто в случае спаивания плат пока не использует эти 7 отверстий, так что минимальное изменение - не менять uaefi

**Comment by rusefillc** [comment]
@Ringenium давай увеличим вырез - там сзади калитка SD карты снизу, а справа интересные компоненты

![image](https://github.com/rusefi/kicad6-libraries/assets/48498823/cc1a5951-d84b-41a0-9923-7018b67c3bb7)

**Comment by Ringenium** [comment]
@rusefillc ready
