### ISSUE TITLE
vertical 26 pin 6473418-1

### ISSUE THREAD

**Issue by rusefillc** [rusefi/kicad6-libraries#3]
We need a footprint for https://www.te.com/usa-en/product-6473418-1.html

**Comment by Nadezhda-n** [comment]
![image](https://user-images.githubusercontent.com/99179773/199248289-f75f1b19-9d04-424f-96ca-21c61138e9ec.png)
ok
https://github.com/rusefi/kicad6-libraries/blob/main/Connectors.kicad_sym
