### ISSUE TITLE
fix silkscreen

### ISSUE THREAD

**Issue by rusefillc** [rusefi/kicad6-libraries#6]
We have just fixed pinout under https://github.com/rusefi/kicad6-libraries/commit/2f85eeb05824ea3dcbd9c62eebf71cfdf49b4e13

@Nadezhda-n i believe we have not yet fixed silkscreen?

pin numbers are now correct, now we need to correct silkscreen

![image](https://user-images.githubusercontent.com/48498823/215358177-d1a29516-0a47-4fbd-a229-807da9903130.png)

**Comment by rusefillc** [comment]
Same
![image](https://user-images.githubusercontent.com/48498823/215358261-aa7510df-c51c-4466-99e4-5eab62a178af.png)

**Comment by Nadezhda-n** [comment]
![image](https://user-images.githubusercontent.com/99179773/215408046-db915d6c-52fe-46aa-ab4a-d3d2f2550437.png)
![image](https://user-images.githubusercontent.com/99179773/215408451-58b2cb46-1709-4353-9698-f467caba1688.png)

**Comment by rusefillc** [comment]
Ой, ой ой. У разъёма всё-таки только номера пинов, конкретика плат не имеет отношения к разъёму

**Comment by Nadezhda-n** [comment]
> Ой, ой ой. У разъёма всё-таки только номера пинов, конкретика плат не имеет отношения к разъёму

то есть просто откатить?

**Comment by Nadezhda-n** [comment]
откатила
![image](https://user-images.githubusercontent.com/99179773/215468398-7d51b583-13ce-4c92-9fa1-e85ef54567b1.png)
![image](https://user-images.githubusercontent.com/99179773/215468476-e3be6b01-041a-496f-bec8-092d9950dab8.png)

**Comment by Nadezhda-n** [comment]
Вот после обновления на alphax_8ch, видимо, забыли обновить шелкографию
![image](https://user-images.githubusercontent.com/99179773/215468922-5b86b685-e860-4e1a-b317-d35b0403781b.png)
![image](https://user-images.githubusercontent.com/99179773/215468998-b65e281a-b099-4875-a5a2-cbb6ea551d03.png)

**Comment by Nadezhda-n** [comment]
https://github.com/rusefi/kicad6-libraries/issues/1#issuecomment-1383657221

**Comment by rusefillc** [comment]
@Nadezhda-n says not an issue

**Comment by rusefillc** [comment]
https://github.com/rusefi/kicad6-libraries/commit/504d7637907d1f0f1998c72d9fc889bb5b4b8c74 reverted as https://github.com/rusefi/kicad6-libraries/commit/11b6a3f284667ebd219adb9be32a7d54ab477429
